### PR TITLE
Rename/clarify RepeatFailedTest (#233)

### PR DESCRIPTION
**Pull request by Bukama**
This draft emerges from #233

This draft improves the documentation and adds more tests for the `@RepeatFailedTest` to point out that `@Test` and `@TestTemplate` should not be combined.

I was trying to add a new method in `PioneerAnnotationUtils` like `isOnlyOneTestAnnotationPresent` which was not a problem. But I was unsure how to throw an exception as the method which checks if the test template must be applied or not, because this would break all other tests which should not executed by the extension.

I threw it away because I noticed that there is already a warning, when such misconfiguration is present (which seems to be printed for every annotation):

> Apr. 23, 2020 10:59:36 NACHM. org.junit.jupiter.engine.discovery.JavaElementsResolver logMultipleTestDescriptorsForSingleElement
WARNUNG: Possible configuration error: method [void org.junitpioneer.jupiter.RepeatFailedTestTests$RepeatFailedTestTestCase.invalidConfigurationWithTest()] resulted in multiple TestDescriptors [org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor, org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor]. This is typically the result of annotating a method with multiple competing annotations such as @Test, @RepeatedTest, @ParameterizedTest, @TestFactory, etc.
> Apr. 23, 2020 10:59:36 NACHM. org.junit.jupiter.engine.discovery.JavaElementsResolver logMultipleTestDescriptorsForSingleElement
WARNUNG: Possible configuration error: method [void org.junitpioneer.jupiter.RepeatFailedTestTests$RepeatFailedTestTestCase.invalidConfigurationWithTest()] resulted in multiple TestDescriptors [org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor, org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor]. This is typically the result of annotating a method with multiple competing annotations such as @Test, @RepeatedTest, @ParameterizedTest, @TestFactory, etc.

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Comment by nicolaiparlog** [comment]
Proposed commit message:

```
Rename `RepeatFailedTest` to `RetryingTest`

#233 reported a problem that was eventually tracked down to
`@RepeatFailedTest` and `@Test` being both applied to the same
method. While the extension's documentation clearly advises against
that, we think the name contributed to the confusion.
`@RepeatFailedTest` may sound too much like needing to be applied to
a method that is already a test, i.e. already annotated with `@Test`.
We hope that `@RetryingTest` prevents that. 
```

**Comment by nicolaiparlog** [comment]
:warning: We need to check whether the docs were updated as well.

**Comment by Bukama** [comment]
Docs updated, build successful locally

**Comment by aepfli** [comment]
we do have to be careful with renaming and deleting annotations. I do not think that it is a nice move, to just rename it. I think we do have a responsibility as a library maintainer to allow an easy migration. Hence that i am more a fan of deprecation, and dedicated information, when this annotation is gonna get deleted. so our users have time to react to this, instead of being forced to do this immediately. What is your take on that?

**Comment by Bukama** [comment]
> we do have to be careful with renaming and deleting annotations. I do not think that it is a nice move, to just rename it. I think we do have a responsibility as a library maintainer to allow an easy migration. Hence that i am more a fan of deprecation, and dedicated information, when this annotation is gonna get deleted. so our users have time to react to this, instead of being forced to do this immediately. What is your take on that?

I see you point and in general I'm totally with you. But as already mentioned somewhere else (don't find it, maybe it was on Discord or Stream) we have not released 1.0 yet, so I think it's okay to rename the feature (as done my @nicolaiparlog )

**Comment by nicolaiparlog** [comment]
I agree @aepfli, but that's why we're doing it now before releasing 1.0. After that, we definitely have to give users time to migrate.

**Pull request merged**
