### PR TITLE
Updating docs with a guide to create and work with a fork

### PR DESCRIPTION
**Pull request by Bukama**
To avoid branch conflicts like we had (I think) two weeks ago and do help new contributors to get to work I've updated the docs by adding a guide on how to create and work with a fork.

As this was spontaneous idea there's no issue for this addional documentation.

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Comment by aepfli** [comment]
maybe we should also reference https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks

**Comment by Bukama** [comment]
> maybe we should also reference https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks

Added, thanks

**Comment by nicolaiparlog** [comment]
I'm not convinced that `CONTRIBUTING.md` is the best place for this how-to. I prefer the file to stay lean and only discuss project specifics. If we start explaining the underlying tools, the file will be huge. Let's discuss in #205.

**Comment by Bukama** [comment]
Hm after the rebase all files that were rebased are shown as changed... I'll create a new PR

**Pull request closed without merging**
