### PR TITLE
Convert build scripts to Kotlin DSL

### PR DESCRIPTION
**Pull request by marcphilipp**
The Kotlin DSL allows for a better editing experience.

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Comment by marcphilipp** [comment]
Hmm, not sure what happened in the AppVeyor build.

@nicolaiparlog Could you please restart it to see if it was a temporary glitch?

**Comment by nicolaiparlog** [comment]
People be like "incremental commits are valuable" - then people be like "let's replace a file with 'valuable' history with a new one". 🤨 Just kidding, though, I'm totally fine with this. :wink: 

[Rebuild failed as well](https://ci.appveyor.com/project/nicolaiparlog/junit-pioneer/builds/27910639).

**Comment by nicolaiparlog** [comment]
Build log contains this section:

> * Task :buildSrc:assemble
> Skipping task ':buildSrc:assemble' as it has no actions.
> :buildSrc:assemble (Thread[Daemon worker,5,main]) completed. Took 0.0 secs.
> :buildSrc:compileTestJava (Thread[Daemon worker,5,main]) started.

Later:

> * What went wrong:
> Task 'assemble' not found in root project 'junit-pioneer'.

**Comment by marcphilipp** [comment]
> People be like "incremental commits are valuable" - then people be like "let's replace a file with 'valuable' history with a new one". 🤨 Just kidding, though, I'm totally fine with this. :wink: 

Well, I did rename and modify them... only Git doesn't care and thinks they're too different. This is clearly a bug if you ask me (but you don't). 😉

**Comment by marcphilipp** [comment]
I'm not sure what AppVeyor is doing, but this looks strange:

```
> Configure project :
Evaluating root project 'junit-pioneer' using build file 'C:\projects\junit-pioneer\build.gradle'.
All projects evaluated.
```

Why is there a `build.gradle` when it's clearly deleted on the PR branch?

**Comment by nicolaiparlog** [comment]
Caching? The failing build contains this in line 6:

> Cache 'C:\Users\appveyor\.gradle\caches' - Invalidated as some dependencies (build.gradle) have changed

Sounds like the cache is invalidated, but... maybe not?

The failing build is the one building the hypothetical merge. Since there is no reason to believe that that will actually be a problem, I'll just overrule AppVeyor.

**Comment by nicolaiparlog** [comment]
[Yep](https://travis-ci.org/junit-pioneer/junit-pioneer/builds/594813577?utm_source=github_status&utm_medium=notification), [yep](https://ci.appveyor.com/project/nicolaiparlog/junit-pioneer/builds/27943706)! :+1:

**Pull request merged**
