### PR TITLE
Ascii docs convert

### PR DESCRIPTION
**Pull request by DhirajSardar**
Convert README.md to README.adoc (#656)

This commit introduces the conversion of the README.md file to the
README.adoc format. The addition of the README.adoc file aims to replace
the existing README.md file with its equivalent in AsciiDoc format.

related to:#656

Please review this pull request.

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [ ] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [ ] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [ ] Site documentation in `.adoc` file references demo in `src/demo/java` instead of containing code blocks as text
* [ ] Only one sentence per line (especially in `.adoc` files)
* [ ] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [ ] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [ ] The `package-info.java` contains information about the new extension

Code
* [ ] Code adheres to code style, naming conventions etc.
* [ ] Successful tests cover all changes
* [ ] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [ ] Tests use [AssertJ](https://assertj.github.io/doc/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [ ] A prepared commit message exists
* [ ] The list of contributions inside `README.md` mentions the new contribution (real name optional)

### CODE REVIEW

**Comment by Michael1993** [comment]
Hey @DhirajSardar, thank you for your interest in the project! Could you cherry-pick your commit so it's on the main branch instead of my PR?

**Comment by DhirajSardar** [comment]
Hey @Michael1993 can you please clarify little bit more what I am supposed to do ?

**Comment by Michael1993** [comment]
@DhirajSardar Sure. Start on your own branch.
```
git log (this will print out the hash of your commit. copy it)
git checkout main
git checkout -b <new branch name> (this creates a new branch and checks it out)
git cherry-pick <your commit hash> -n (this moves your commit on top of main, without committing the result)
git branch -D <your branch name> (this deletes your branch)
git push (push your changes)
```

Then you can open a new PR that does not include my commits from another PR.

**Comment by DhirajSardar** [comment]
Hey Can I keep the commit message as a previous one or should I create new commit or shall I proceed using empty commit @Michael1993 
? can you please enlighten this. I am in confusion actually.

**Pull request closed without merging**
