### PR TITLE
Resolve Playwright basic types as parameters

### PR DESCRIPTION
**Pull request by nipafx**
Work in progress...

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Comment by nipafx** [comment]
Looks like Gradle refuses to pull Playwright onto the module path:

```sh
$ ./gradlew -PmodularBuild --debug build
> -classpath
> 	com.microsoft.playwright/playwright/0.180.0/d42ada11f717b3146780e738b4a4be17bb851d5c/playwright-0.180.0.jar
> 	com.microsoft.playwright/driver-bundle/0.180.0/b00959eabb478d7ca7746ea5f251a8eb762b20b2/driver-bundle-0.180.0.jar
> 	com.microsoft.playwright/driver/0.180.0/f7d39710fefe03959ab51900afcf5b68b7445db5/driver-0.180.0.jar
> --module-path /org.junit.jupiter/junit-jupiter-params/5.5.2/e0659722923bd9fdfa08602e2da22bd5a9d354e8/junit-jupiter-params-5.5.2.jar
> 	org.junit.jupiter/junit-jupiter-api/5.5.2/6393db7e4c0265152d8fc4ff146633d1a7d36c47/junit-jupiter-api-5.5.2.jar
> 	org.junit.platform/junit-platform-launcher/1.5.2/bca9d635ae55b37540e6e26e3e08ea0977516fe3/junit-platform-launcher-1.5.2.jar
> 	org.junit.platform/junit-platform-engine/1.5.2/d5697f6ebe0b4d08c0210b5b98b4e1a40f40dfc6/junit-platform-engine-1.5.2.jar
> 	org.junit.platform/junit-platform-commons/1.5.2/9703df63b65d415b2a027d43ce908c625b3aedce/junit-platform-commons-1.5.2.jar
> 	com.google.code.gson/gson/2.8.6/9180733b7df8542621dc12e21e87557e8c99b8cb/gson-2.8.6.jar
> 	org.apiguardian/apiguardian-api/1.1.0/fc9dff4bb36d627bdc553de77e1f17efd790876c/apiguardian-api-1.1.0.jar
> 	org.opentest4j/opentest4j/1.2.0/28c11eb91f9b6d8e200631d46e20a7f407f2a046/opentest4j-1.2.0.jar
```

Maybe because it's the only dependency that doesn't have a module declaration? GSON does and (I assume) so do the JUnit JARs. If so, 😭 .

**Comment by Bukama** [comment]
Yeah, have the same prob with the CSV-Lib in Test-reports

**Comment by nipafx** [comment]
I decided to table this for now.

**Comment by nipafx** [comment]
Let's keep the branch around, though.

**Pull request closed without merging**
