### PR TITLE
Update JUnit and Java

### PR DESCRIPTION
**Pull request by beatngu13**
In contrast to what is partly written in #818, I did _not_ upgrade the JUnit version in `gradle.properties`, as ["Pioneer aims to use the lowest JUnit 5 version that supports Pioneer’s feature set"](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.adoc#updating-junit-5).

Proposed commit message:

```
Update JUnit (Pioneer) and Java (CI) (#818 / #826)

This PR updates the JUnit dependency for Pioneer from 5.10.2 to
5.11.2. It also updates the latest included Java version for CI from 21 to
23.

Since the engine behavior changed with JUnit 5.11.0 (see
https://github.com/junit-team/junit5/commit/9af6ca4ba66e5bc3ba4a93b47333816853dd34f4#diff-58dca140b6249c0d7f76a8056994eb6762b71bd2f79cc28106e5391d16d23245), some assertions are updated as well.

Closes: #818
PR: #826
```

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.adoc#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [ ] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [ ] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [ ] Site documentation in `.adoc` file references demo in `src/demo/java` instead of containing code blocks as text
* [ ] Only one sentence per line (especially in `.adoc` files)
* [ ] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [ ] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [ ] The `package-info.java` contains information about the new extension

Code (general)
* [ ] Code adheres to code style, naming conventions etc.
* [ ] Successful tests cover all changes
* [ ] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [ ] Tests use [AssertJ](https://assertj.github.io/doc/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.adoc#assertions) (which are based on AssertJ)

Code (new package)
* [ ] The new package is exported in `module-info.java`
* [ ] The new package is also present in the tests
* [ ] The new package is opened for reflection to JUnit 5 in `module-info.java`
* [ ] The new package is listed in the contribution guide

Contributing
* [x] A prepared commit message exists
* [ ] The list of contributions inside `README.adoc` mentions the new contribution (real name optional)

### CODE REVIEW

**Comment by beatngu13** [comment]
`ResourceTests` are failing starting with JUnit Jupiter 5.11.0 (5.10.5) works just fine. On our side, we expect certain exceptions to be thrown when `close()` fails. However, now it is always:

```text
org.junit.platform.commons.JUnitException: Failed to close extension context
```

I believe this is caused by this change:

https://github.com/junit-team/junit5/commit/9af6ca4ba66e5bc3ba4a93b47333816853dd34f4#diff-58dca140b6249c0d7f76a8056994eb6762b71bd2f79cc28106e5391d16d23245

Additional links:

* 5.11.0 release notes: https://junit.org/junit5/docs/current/release-notes/index.html#release-notes-5.11.0
* Full changelog: https://github.com/junit-team/junit5/compare/r5.10.5...r5.11.0

**Comment by beatngu13** [comment]
As this is new engine behavior, we can't really do much. We have to consider that we have a matrix build which includes both JUnit Jupiter versions, that is, new (latest release, currently 5.11.2; and old (Pioneer dependency, currently 5.10.1) behavior. Therefore, I think we have two options:

1. Upgrade to 5.11.2 (or 5.11.0) and modify the assertions accordingly (I already did that locally). This removes 5.10.1 from the build matrix.
2. Disable the tests for 5.11+.

I think I would go with 1.

**Comment by Bukama** [comment]
> As this is new engine behavior, we can't really do much. We have to consider that we have a matrix build which includes both JUnit Jupiter versions, that is, new (latest release, currently 5.11.2; and old (Pioneer dependency, currently 5.10.1) behavior. Therefore, I think we have two options:
> 
> 1. Upgrade to 5.11.2 (or 5.11.0) and modify the assertions accordingly (I already did that locally). This removes 5.10.1 from the build matrix.
> 2. Disable the tests for 5.11+.
> 
> I think I would go with 1.

Thanks for the analysis. I think the step to only use the new test engine would be a valid step as people often just update JUnit dependencies to the newest anyway.

**Review by Bukama — APPROVED** [review]

**Comment by Bukama** [comment]
The approve above obviously is meant about the changes in the configuration file so far. That's why I also self-requested another review.

**Pull request merged**
