### PR TITLE
An alternative solution to PioneerAnnotationUtils (#389 / #388)

### LINKED ISSUE #389: Handle duplication of PioneerAnnotationUtils
_by @Michael1993 _

PioneerAnnotationUtils is currently not public, but is used by
multiple classes in different packages. Previously, we created
a copy of the class with reflection magic, which is a fragile
approach. This PR introduces a test, that checks (and copies) the
PioneerAnnotationUtils in different packages. The test fails if
the classes don't match.

### PR DESCRIPTION
**Pull request by Michael1993**
closes #389

Signed-off-by: Mihaly Verhas <misi.verhas@gmail.com>

Proposed commit message:

```
Create test-time copy of PioneerAnnotationUtils (#389 / #388)

PioneerAnnotationUtils is currently not public, but is used by
multiple classes in different packages. Previously, we created
a copy of the class with reflection magic, which is a fragile
approach. This PR introduces a test, that checks (and copies) the
PioneerAnnotationUtils in different packages. The test fails if
the classes don't match.

closes: #389
PR: #388
```

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Code
* [X] Code adheres to code style, naming conventions etc.
* [X] Successful tests cover all changes
* [X] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [X] Tests use [AssertJ](https://joel-costigliola.github.io/assertj/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [X] A prepared commit message exists
* [ ] The list of contributions inside `README.md` mentions the new contribution (real name optional) 

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Comment by Michael1993** [comment]
Duplication is expected, code coverage should not be considered for duplicate class - or we can duplicate the tests too, I guess. 🤔

**Comment by Bukama** [comment]
I‘ll review, when I‘m back home (mobile is too small and the app sucks). But one thing I can tell you right now that Nicolai will bring up: We need an issue for that topic :)

**Review by Bukama — COMMENTED** [review]
I don't like the that we copy our own classes only because they are not public.

I vote to make them public an use them in the way classes are used to. 

Yes without module system this opens the class for others, but why not? If anyone wants to use it to find annotations on their own extension, why not?

**Comment by nipafx** [comment]
I'm sorry-not-sorry, but I'll close this one, ok? :)

**Pull request closed without merging**
