### PR TITLE
Use Gradle properties

### LINKED ISSUE #46: Use gradle.properties for login credentials
Currently `build.gradle` defines the user's password for the Maven snapshot repository as follows:

```
ext {
    // the password needs to be specified via command line
    snapshotRepoPass = project.hasProperty('snapshotRepoPass') ? project.getProperty('snapshotRepoPass') : ''
}
```

This requires the user to enter the password on the command line, which commits it to CLI history. A more sensible way to configure this would be a user-local `gradle.properties` file [as explained here](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_properties_and_system_properties).

The opportunity should be used to make the username configurable as well and additionally use a more sensible property name.

* [ ] configure `build.gradle` to use properties defined in `gradle.properties`
* [ ] update `.travisyml` and Travis configuration to use the new mechanism
* [ ] use the opportunity to document the publication process

### PR DESCRIPTION
**Pull request by nicolaiparlog**
Maven user name and password can now be defined as `gradle.properties` _or_ as command line properties.

Closes #46.

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](../CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Comment by nicolaiparlog** [comment]
@smoyer64 Can you give this branch a try to publish to Maven Central? Besides checking whether it works, you can also check whether the documentation suffices - see [updated `README`](https://github.com/junit-pioneer/junit-pioneer/pull/47/files#diff-04c6e90faac2675aa89e2176d2eec7d8R22) for that.

**Comment by nicolaiparlog** [comment]
Argh, CI builds fail because the servers do not define the command line arguments, which means they also fail for anyone else who doesn't have. I have to fix that but you can still try out whether publication works.

**Comment by mkobit** [comment]
You can use `project.findProperty('propName')` and it will be null for local builds and whatever was specified on the CI System when it runs there.

**Comment by nicolaiparlog** [comment]
@mkobit Yes, I did that earlier for the command line flag but for some reason forgot I had to do it here, too. Just rediscovered it. :wink:

**Comment by nicolaiparlog** [comment]
Oh, I did `hasProperty`/`getProperty` - `findProperty` is much better, thanks for the hint.

**Comment by nicolaiparlog** [comment]
Proposed commit message:

```
Read Maven Central credentials from Gradle properties (#46 / #47)

To allow all maintainers to publish to Maven Central the credentials
are read from the Gradle properties file. This did not actually
require a technical change as the existing mechanism already did that
implicitly (and without my knowledge). New is that the user name as
well as the password is read from properties and that CONTRIBUTING.md
describes the process.
```

**Comment by nicolaiparlog** [comment]
@smoyer64 Can you give this a try, so I can merge and continue working on release pipeline?

**Comment by smoyer64** [comment]
@nicolaiparlog I tried to publish a both a snapshot and a release this morning.  When publishing the snapshot, it failed with the message:

```
 * What went wrong:
Execution failed for task ':publishCompletePublicationToMavenSnapshotRepository'.
> Failed to publish publication 'complete' to repository 'MavenSnapshot'
   > Failed to deploy artifacts: Could not transfer artifact org.junit-pioneer:junit-pioneer:jar:0.001-20170623.111606-1 from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Could not write to resource 'org/junit-pioneer/junit-pioneer/0.001-SNAPSHOT/junit-pioneer-0.001-20170623.111606-1.jar'
```

When trying to publish the release, it failed to sign the artifacts since I don't have the signing key on my machine.  Since we're "always" using branches and PRs, should we have the triggered CI build on master perform the releaseSnapshot task?

I've added you on Keybase if you need to share anything securely.

**Comment by nicolaiparlog** [comment]
Now that everything's merged, can you have a look at the [docs on publishing](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#publishing) and proceed as they describe? You should be able to publish snapshots and releases, using your credentials for each. You can use any PGP key want as long as it's published on a public key server. It may also have to be bound to the email address you registered on Sonatype (it would make sense and is the case for me but I don't know whether Sonatype checks).

If you have problems, can you run your gradle command with `--stacktrace` and open an issue for it?

**Comment by smoyer64** [comment]
I was using the publishing instructions in CONTRIBUTING.md - it turns out that my problem was that ```mavenUsername != mavenUserName```.  I hadn't thought about publishing a release with my PGP key but that should also work fine.  When we publish artifacts at Penn State, we use a key that was created specifically for our CI server so that all our releases are signed with the same key.

**Pull request merged**
