### PR TITLE
Moving away from bintray

### PR DESCRIPTION
**Pull request by Michael1993**
I am fairly certain I broke nothing.

PR Checklist:

* [ ] Is this documented? No. Not at all.
* [ ] Will this publish to sonatype only or to maven central? Heck if I know, I just followed a quickstart guide.
* [ ] Why didn't you delete the bintray task from the build? I... don't know? Probably should've done that.
* [ ] Does Nicolai still need to work on this? Yes.

### CODE REVIEW

**Review by aepfli — APPROVED** [review]
should we maybe first do a run with just closin and not releasing? better save than sorry :D

> Please bear in mind that - especially on the initial project publishing to Maven Central - it might be wise to call just publishToSonatype closeSonatypeStagingRepository and manually verify that the artifacts placed in the closed staging repository in Nexus looks ok. After that, the staging repository might be dropped (if needed) or manually released from the Nexus UI.

https://github.com/gradle-nexus/publish-plugin/blob/master/README.md#71

but overall lgtm - and it wasnt that hard wasnt it?

**Review by Bukama — COMMENTED** [review]
I have no clue about this topic so don't expect anything from me aside this comment 👼

**Comment by aepfli** [comment]
https://github.com/junit-pioneer/junit-pioneer/issues/435#issuecomment-823103345 added @nipafx  link to the issue, and also a discussion point.

For me this one is good to go as the first iteration, and signing could be added at a later stage

**Comment by nipafx** [comment]
Two release builds failed with the same error:

```
* What went wrong:
Execution failed for task ':initializeSonatypeStagingRepository'.
> Failed to load staging profiles, server at https://oss.sonatype.org/service/local/ responded with status code 401
```

The second ran with a freshly generated Nexus token, so it doesn't fail because of invalid credentials.

**Comment by aepfli** [comment]
i am just doing a little bit of research and add links which might be useful
- https://stackoverflow.com/a/50337603/3708208

**Comment by aepfli** [comment]
still 401 suggest an issue with the credentials - should we maybe try to use username and password without a token?

**Comment by nipafx** [comment]
Turns out, if you correctly configure the GitHub secrets, it actually works. 😁

**Comment by aepfli** [comment]
```
 > Task :publishMavenPublicationToSonatypeRepository
Caching disabled for task ':publishMavenPublicationToSonatypeRepository' because:
  Build cache is disabled
Task ':publishMavenPublicationToSonatypeRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Uploading to https://oss.sonatype.org/service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036
Publishing to repository 'sonatype' (https://oss.sonatype.org/service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036)
Uploading junit-pioneer-1.3.28.jar to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/1.3.28/junit-pioneer-1.3.28.jar
Uploading junit-pioneer-1.3.28.pom to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/1.3.28/junit-pioneer-1.3.28.pom
Uploading junit-pioneer-1.3.28.pom.asc to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/1.3.28/junit-pioneer-1.3.28.pom.asc
Uploading junit-pioneer-1.3.28.module to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/1.3.28/junit-pioneer-1.3.28.module
Uploading junit-pioneer-1.3.28-sources.jar to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/1.3.28/junit-pioneer-1.3.28-sources.jar
Uploading junit-pioneer-1.3.28.jar.asc to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/1.3.28/junit-pioneer-1.3.28.jar.asc
Uploading junit-pioneer-1.3.28-javadoc.jar to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/1.3.28/junit-pioneer-1.3.28-javadoc.jar
Uploading junit-pioneer-1.3.28-sources.jar.asc to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/1.3.28/junit-pioneer-1.3.28-sources.jar.asc
Uploading junit-pioneer-1.3.28.module.asc to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/1.3.28/junit-pioneer-1.3.28.module.asc
Uploading junit-pioneer-1.3.28-javadoc.jar.asc to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/1.3.28/junit-pioneer-1.3.28-javadoc.jar.asc
Resource missing. [HTTP GET: https://oss.sonatype.org/service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/maven-metadata.xml]
Uploading maven-metadata.xml to /service/local/staging/deployByRepositoryId/orgjunit-pioneer-1036/org/junit-pioneer/junit-pioneer/maven-metadata.xml
:publishMavenPublicationToSonatypeRepository (Thread[Daemon worker,5,main]) completed. Took 0.727 secs.
:publishToSonatype (Thread[Daemon worker,5,main]) started.
```
publishing to staging repository worked

**Pull request merged**
