### PR TITLE
Update StdOutputStream to keep trailing empty lines

### LINKED ISSUE #750: StdOutputStream final linefeed ambiguity.
StdOutputStream's capturedLines() method takes the string output and splits it by the system line separator, returning an array.

The returned array will be identical whether or not the final line written to standard out has a newline at the end, as String.split treats the split character and the end of the string the same.

You therefor can not test that the final line written to STDOUT ends with a linefeed.

This is a nitpick but I suppose it could matter to someone.

I'd suggest simply adding an additional public String capturedString() method that returns the entire output unmolested.

### PR DESCRIPTION
**Pull request by Michael1993**
Closes #750 

Proposed commit message:

```
${action} (${issues} / ${pull-request}) [max 70 characters]

${body} [max 70 characters per line]

${references}: ${issues}
PR: ${pull-request}
```

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [ ] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [ ] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [ ] Site documentation in `.adoc` file references demo in `src/demo/java` instead of containing code blocks as text
* [ ] Only one sentence per line (especially in `.adoc` files)
* [ ] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [ ] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [ ] The `package-info.java` contains information about the new extension

Code
* [ ] Code adheres to code style, naming conventions etc.
* [ ] Successful tests cover all changes
* [ ] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [ ] Tests use [AssertJ](https://assertj.github.io/doc/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [ ] A prepared commit message exists
* [ ] The list of contributions inside `README.md` mentions the new contribution (real name optional)

### CODE REVIEW

**Review by Bukama — APPROVED** [review]
Put a nice commit message on it and you are ready to merge :)

**Comment by nipafx** [comment]
After a lot of qualms, I settled on the basic assumption that every line, whether printed to `System.out` or read from `System.in`, ends with a newline (except with `System.out.println`). That leads to:

* print("Foo") ~> ...
  * capturedString: "Foo"
  * capturedLines: [ "Foo" ]
* println("Foo") ~> ...
  * capturedString: "Foo%n"
  * capturedLines: [ "Foo" ]
* println("Foo"), println() ~> ...
  * capturedString: "Foo%n%n"
  * capturedLines: [ "Foo", "" ]
* readln: "Foo" ~> ...
  * capturedString: "Foo%n"
  * capturedLines: [ "Foo" ]
* readln: "Foo", "" ~> ...
  * capturedString: "Foo%n%n"
  * capturedLines: [ "Foo", "" ]

The new behavior still needs to be documented. And the issue needs to prominently explain that the behavior changed and what the fix is. We can later copy-paste that to the release notes.

**Comment by nipafx** [comment]
I described the behavior in the feature doc. Can you take a look @Michael1993?

Once we agree on the phrasing and details in the there, we can expand it to the Javadoc (or at least add a reference there) and issue, so we have something to copy to the release notes.

**Review by Michael1993 — COMMENTED** [review]
The documentation looks fine to me.

**Pull request merged**
