### PR TITLE
Gradle 6.6.1

### PR DESCRIPTION
**Pull request by sullis**
---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [ ] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [ ] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [ ] Only one sentence per line (especially in `.adoc` files)
* [ ] Javadoc uses formal style, while sites documentation may use informal style (see #265)

Documentation (new extension)
* [ ] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [ ] The `package-info.java` contains information about the new extension

Code
* [ ] Code adheres to code style, naming conventions etc.
* [ ] Successful tests cover all changes
* [ ] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks (see #164)
* [ ] Tests use [AssertJ](https://joel-costigliola.github.io/assertj/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [ ] A prepared commit message exists
* [ ] The list of contributions inside `README.md` mentions the new contribution (real name optional) 

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Review by aepfli — APPROVED** [review]
LGTM

**Review by beatngu13 — APPROVED** [review]

**Comment by Bukama** [comment]
@aepfli @beatngu13 Did you check the failing builds? I mean you approved the PR, but the failing builds are not only our "suspicients" (aka windows like in #324 )

**Comment by beatngu13** [comment]
@Bukama or @aepfli could you please try to re-run the failed builds?

**Comment by aepfli** [comment]
i retriggered, and it seems like sonar analysis is causing some troubles. i will investigate

**Comment by Bukama** [comment]
Mainbuild still failing. So I vote not to merge this until it works again.

**Comment by aepfli** [comment]
Agreed, the changes still look fine. And it seems more like a GitHub action
limitation than an actual code issue.

**Comment by Bukama** [comment]
When GitHub Actions is not able to run with Gradle 6.6.1 we should not merge to avoid even more breaking builds.

**Review by beatngu13 — CHANGES_REQUESTED** [review]
Since this Gradle update causes several builds to break and, therefore, needs further investigation, I withdraw my approval.

@sullis thx a lot for the PR, would you mind having a closer look as the original author? You should be able to check the builds in your fork. Otherwise, we have to wait until @aepfli or myself find some time.

**Comment by Bukama** [comment]
According to log the sonar runs out of memory. maybe this solution helps
`mavenOptions: '-Xmx5500m'`

Saw this in https://github.com/odpi/egeria/pull/2175/files

**Comment by beatngu13** [comment]
@Bukama sounds reasonable.

I'm not a maintainer, so I cannot push to the author's branch/repo. If someone else could try to add the following to the `gradle.properties`:

```properties
# Ensure sufficient heap size, especially for Sonar.
org.gradle.jvmargs=-Xmx4g
```

According to the [GitHub docs](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources), the VM has 7 GB of RAM memory. So the 4 GB should be available.

**Comment by sullis** [comment]
> @Bukama sounds reasonable.
> 
> I'm not a maintainer, so I cannot push to the author's branch/repo. If someone else could try to add the following to the `gradle.properties`:
> 
> ```ini
> # Ensure sufficient heap size, especially for Sonar.
> org.gradle.jvmargs=-Xmx4g
> ```
> 
> According to the [GitHub docs](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources), the VM has 7 GB of RAM memory. So the 4 GB should be available.

Done.  All checks pass.

**Review by beatngu13 — APPROVED** [review]

**Pull request merged**
