### PR TITLE
Inherit entry-based annotations

### LINKED ISSUE #448: Annotations like @SetSystemProperty are not inherited
The following test fails:

```java
@SetSystemProperty(key = "set prop A", value = "new A")
class SuperClass { }

@Nested
class TestClass extends SuperClass {

	@Test
	void shouldSetSystemPropertyToValue() {
		assertThat(System.getProperty("set prop A")).isEqualTo("new A");
	}

}
```

Unless I'm missing something, it stands to reason that it should pass because it should inherit the annotation from the super class. Am I missing something?

### PR DESCRIPTION
**Pull request by beatngu13**
Closes #448.

Proposed commit message:

```
Inherit entry-based annotations (#448 / #449)

The following entry-based annotations can now be inherited:

* `ClearEnvironmentVariable`
* `SetEnvironmentVariable`
* `ClearSystemProperty`
* `SetSystemProperty`

This also includes the corresponding repeatable annotations.

Closes: #448
PR: #449
```

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [ ] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [ ] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [ ] Only one sentence per line (especially in `.adoc` files)
* [ ] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [ ] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [ ] The `package-info.java` contains information about the new extension

Code
* [x] Code adheres to code style, naming conventions etc.
* [x] Successful tests cover all changes
* [ ] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [x] Tests use [AssertJ](https://joel-costigliola.github.io/assertj/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [x] A prepared commit message exists
* [x] The list of contributions inside `README.md` mentions the new contribution (real name optional) 

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Comment by beatngu13** [comment]
@Michael1993 probably makes sense. Will have a look tonight, for which annotations this is actually useful. I assume only where the target `ElementType.TYPE` is included?!

**Review by aepfli — APPROVED** [review]
LGTM

**Comment by beatngu13** [comment]
>Will have a look tonight […]

As you can see, I haven't had time so far. Shall I convert this into draft? Will try to compose a list of affected annotations ASAP.

**Review by Bukama — APPROVED** [review]
One of those tiny things - nice fix!

**Pull request merged**
