### PR TITLE
Updates to RangeSources

### LINKED ISSUE #671: Make RangeSource annotation non-repeatable
Initially, `RangeSource` annotations were non-repeatable. They were made repeatable for the `CartesianProductTestExtension`. Since that has been/will be removed in 2.0, it no longer makes sense for the `RangeSource` annotations to be repeatable, so we should make them non-repeatable again.

Additionally, they should work with other `ArgumentsSource` annotations that are not `RangeSource`, since that's how JUnit's built-in annotations work with `ParameterizedTest` so some users might expect that behaviour.

### PR DESCRIPTION
**Pull request by Michael1993**
Closes #671

Proposed commit message:

```
Make RangeSource annotations non-repeatable (#671 / #670)

RangeSource annotations were made repeatable for the
CartesianProductTest extension. With the removal of the old
extension, RangeSources should be non-repeatable again.

This commit also fixes a bug that threw an exception when multiple
ArgumentSources were present on a test with a RangeSource. Now only
multiple RangeSources are not permitted, other ArgumentSources are
accepted.

Closes: #671 
PR: #670
```

TODO:

* [x] Document limitation of using multiple `RangeSource` annotations with a single `ParameterizedTest`?
* [x] Add more tests

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [x] There is documentation (Javadoc and site documentation; added or updated)
* [x] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [x] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [x] Site documentation in `.adoc` file references demo in `src/demo/java` instead of containing code blocks as text
* [x] Only one sentence per line (especially in `.adoc` files)
* [x] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [x] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [x] The `package-info.java` contains information about the new extension

Code
* [x] Code adheres to code style, naming conventions etc.
* [x] Successful tests cover all changes
* [x] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [x] Tests use [AssertJ](https://assertj.github.io/doc/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [x] A prepared commit message exists
* [x] The list of contributions inside `README.md` mentions the new contribution (real name optional)

### CODE REVIEW

**Review by aepfli — APPROVED** [review]
lgtm

**Comment by Michael1993** [comment]
No automated checks? 😭

**Comment by aepfli** [comment]
> No automated checks? sob

strange actually the branch should be covered within 
https://github.com/junit-pioneer/junit-pioneer/blob/d9e926ee705832607fa08672c28f42dc936ea27b/.github/workflows/build.yml#L13-L19

maybe we remove the branches directive as it is redundant anyways, see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-based-on-the-head-or-base-branch-of-a-pull-request

**Comment by Bukama** [comment]
> // EDIT: looks like we do have a bug in the yml and it should be actually `**`

I checked that in history, but it has always be single star. I opened #673 for the bug (to don't have it mixed with this PR)

**Review by Bukama — APPROVED** [review]
Looks good. I checked docs and there is no way about repeatable annotation. Maybe we should add a sentence or two?

**Comment by Michael1993** [comment]
> Looks good. I checked docs and there is no way about repeatable annotation. Maybe we should add a sentence or two?

There _was_ documentation about this feature in the deprecated `@CartesianProductTest` documentation, I believe? Where else would you like this documented (especially considering we are _removing_ this functionality)?

**Comment by Bukama** [comment]
> > Looks good. I checked docs and there is no way about repeatable annotation. Maybe we should add a sentence or two?
> 
> There _was_ documentation about this feature in the deprecated `@CartesianProductTest` documentation, I believe? Where else would you like this documented (especially considering we are _removing_ this functionality)?

I was thinking about explicity say, that it is not repeatable anymore (as it was in the old one). Like some kind of migration guide note.

**Review by aepfli — APPROVED** [review]

**Comment by Michael1993** [comment]
> > > Looks good. I checked docs and there is no way about repeatable annotation. Maybe we should add a sentence or two?
> > 
> > 
> > There _was_ documentation about this feature in the deprecated `@CartesianProductTest` documentation, I believe? Where else would you like this documented (especially considering we are _removing_ this functionality)?
> 
> I was thinking about explicity say, that it is not repeatable anymore (as it was in the old one). Like some kind of migration guide note.

From a practical standpoint, it was **never** repeatable in the RangeSource context because the RangeSource extension throws an `ExtensionConfigurationException` if there is more than one `RangeSource` on a method, so I don't think that has to be documented for migration.

**Comment by Bukama** [comment]
Please provide a commit message, so we can merge / close this :)

**Pull request merged**
