### PR TITLE
Basic implementation of the ReportEntry feature.

### LINKED ISSUE #134: Add declarative annotation for test authors to add test metadata for report entries
Add in a simple way for test authors to declaratively add test metadata to test containers or methods.

basic example (needs better names in all places)

```java
@ReportEntry(reportKey = "myKey", reportValue = "someValue")
```

### PR DESCRIPTION
**Pull request by Michael1993**
Closes #134 

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Comment by Michael1993** [comment]
I know it looks weird. I don't know how to make it less weird.

**Comment by nicolaiparlog** [comment]
I'm sorry I didn't have time to look at it. Next stream. :)

**Comment by nicolaiparlog** [comment]
Thanks @Michael1993, great work! I added a few tests and Javadoc. Can you add documentation to the `docs` folder? Could be along the lines:

* what's a report entry (one liner, link to user guide)
* how to use test reporter "the normal way" (link to Javadoc)
* how to use the extension with some examples

Remember to also add it to `docs-nav.yml`. :)

**Comment by nicolaiparlog** [comment]
Oh, and we need a commit message. Do you want to propose one?

**Comment by Michael1993** [comment]
I'll leave the commit message to you, I'm not really confident in my ability to properly summarize this feature.

**Comment by Bukama** [comment]
As written in chat, here's my draft for a commit message:

```
Implementing the @ReportEntry extension

With this commit the basic features of the @ReportEntry extension are implemented.
With this extension it's possible to annotate a test case with one or multiple key/value pairs which are published in the test report.

This allows the writer to add individuial meta data to tests in a structed way, without having fixed annotation names (cf. when using the @Tag-annotation).
Simultaneously the extension can be used for further extensions which should provide indivudal annotations to be published in the report as well.
```

**Comment by nicolaiparlog** [comment]
Superseded by #183 (contains these commits plus documentation).

**Pull request closed without merging**
